---
title: "Energie simulaties voor digitale meter"
author: "Jonas Meijerink"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center" , out.width = "100%")
eval_option = F
```


```{r include=FALSE}
### Load necessary libraries
#---------------------------
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)


### Load functions
#-----------------
source("~/Energy-simulations-digital-meter/src/energycost/energy_cost_ecopower.R")
source("~/Energy-simulations-digital-meter/src/energyviz/Function_viz_afname_inname.R")
source("~/Energy-simulations-digital-meter/src/batterysim/Home_battery_simulation.R")
source("~/Energy-simulations-digital-meter/src/dataformat/Change_data_format.R")

### Load data
#------------
Test_31122025 <- read.csv2("~/Energy-simulations-digital-meter/data/Test_31122025.csv")
```

# Introductie {.sidebar}

# Berekening


## Column 2

### Inferno colors

```{r}
df <- Change_data_format(Test_31122025 , tz = "Europe/Brussels")
df$production <- df$production 
```


```{r}
out <- rbind(
  simulate_battery(df, batt_cap = 0, tarief = "vast", energie_kost = energy_cost_ecopower),
  simulate_battery(df, batt_cap = 5, tarief = "vast", energie_kost = energy_cost_ecopower),
  simulate_battery(df, batt_cap = 10, tarief = "vast", energie_kost = energy_cost_ecopower),
  simulate_battery(df, batt_cap = 15, tarief = "vast", energie_kost = energy_cost_ecopower),
  simulate_battery(df, batt_cap = 20, tarief = "vast", energie_kost = energy_cost_ecopower)
             )
```



```{r}
ggplot(out , aes(Timestamp , Kost_Euro, color = Cap)) +
  geom_line() + 
  theme_minimal()
```


# Daily production overview


```{r echo=FALSE, message=FALSE, warning=FALSE}
#plot_prod_vs_cons(Test_20122025, smooth = TRUE)
```

